'use client';

import { useEffect, useRef, useState } from 'react';
import * as maplibregl from 'maplibre-gl';
import { MapboxOverlay } from '@deck.gl/mapbox';
import { ScatterplotLayer } from '@deck.gl/layers';
import { ScenegraphLayer } from '@deck.gl/mesh-layers';
import { GLTFLoader } from '@loaders.gl/gltf';
import 'maplibre-gl/dist/maplibre-gl.css';

// Free Carto dark basemap — no API token required (satisfies the MapLibre,
// no-Mapbox-token decision). Reads well behind glowing vehicle marks.
const BASEMAP = 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json';

const TORONTO = { longitude: -79.384, latitude: 43.685, zoom: 11.5 };

// Vehicle colors, RGB (used for the far-zoom dots + legend).
const COLORS = {
  bus: [225, 29, 46], // TTC red
  streetcar: [245, 158, 11], // amber
  subway: [56, 189, 248], // sky (placeholder until M7)
};

const POLL_MS = 15000;

// LOD: below this zoom render cheap dots; at/above it render 3D models.
const LOD_ZOOM = 13.5;

// Models are true-to-scale meters (12 m bus); a modest scale-up keeps them
// readable at street zoom without looking cartoonish.
const SIZE_SCALE = 1.75;

// Generated by scripts/build-vehicle-models.mjs. Model space: +X forward,
// +Y up, meters, origin at footprint center.
const MODELS = {
  bus: '/transit/models/bus.glb',
  streetcar: '/transit/models/streetcar.glb',
  subway: '/transit/models/subway.glb',
};

// Maps compass bearing (deg clockwise from north) onto deck.gl's
// [pitch, yaw, roll] model orientation for our +X-forward, +Y-up models.
// If vehicles render lying on their side or pointing across their direction
// of travel, these two constants are the knobs to tune.
const MODEL_YAW_OFFSET = 90;
const MODEL_ROLL = 90;
function orientationForBearing(bearing) {
  return [0, MODEL_YAW_OFFSET - (bearing ?? 0), MODEL_ROLL];
}

// Shortest-path bearing interpolation (handles the 350° -> 10° wrap).
function lerpBearing(a, b, t) {
  if (a == null) return b ?? 0;
  if (b == null) return a;
  const d = ((b - a + 540) % 360) - 180;
  return (a + d * t + 360) % 360;
}

export default function TransitMap() {
  const containerRef = useRef(null);
  const mapRef = useRef(null);
  const overlayRef = useRef(null);
  const zoomRef = useRef(TORONTO.zoom);
  // id -> {lon0, lat0, lon1, lat1, b0, b1, tStart, tEnd, type, routeId}
  // Each vehicle glides from its (0) pose to its (1) pose over one poll
  // interval; the rAF loop below samples this every frame so the fleet moves
  // continuously instead of teleporting on each 15s feed refresh.
  const fleetRef = useRef(new Map());
  const [status, setStatus] = useState({ count: 0, updatedAt: null, error: null });

  // Init map + deck overlay once.
  useEffect(() => {
    if (mapRef.current || !containerRef.current) return;

    const map = new maplibregl.Map({
      container: containerRef.current,
      style: BASEMAP,
      center: [TORONTO.longitude, TORONTO.latitude],
      zoom: TORONTO.zoom,
      pitch: 45, // tilted for the 3D view; user can flatten with the control
      attributionControl: { compact: true },
    });
    map.addControl(new maplibregl.NavigationControl({ visualizePitch: true }), 'top-right');
    map.on('move', () => {
      zoomRef.current = map.getZoom();
    });

    // Non-interleaved: deck renders to its own canvas above the map.
    // (interleaved mode crashes against maplibre-gl v6 — deck 9.3's render
    // integration reads the map's render pipeline and hits undefined.height.)
    const overlay = new MapboxOverlay({ interleaved: false, layers: [] });
    map.addControl(overlay);

    mapRef.current = map;
    overlayRef.current = overlay;

    return () => {
      map.remove();
      mapRef.current = null;
      overlayRef.current = null;
    };
  }, []);

  // Poll the live feed and retarget the fleet.
  useEffect(() => {
    let cancelled = false;
    let timer = null;

    async function tick() {
      try {
        const res = await fetch('/api/transit/vehicles', { cache: 'no-store' });
        if (!res.ok) throw new Error(`api ${res.status}`);
        const data = await res.json();
        if (cancelled) return;

        const now = performance.now();
        const fleet = fleetRef.current;
        const seen = new Set();

        for (const v of data.vehicles) {
          seen.add(v.id);
          const cur = fleet.get(v.id);
          if (!cur) {
            // New vehicle: appears in place, no glide-in from nowhere.
            fleet.set(v.id, {
              lon0: v.lon, lat0: v.lat, lon1: v.lon, lat1: v.lat,
              b0: v.bearing, b1: v.bearing,
              tStart: now, tEnd: now + POLL_MS,
              type: v.type, routeId: v.routeId,
            });
          } else {
            // Start the new glide from wherever the vehicle is rendered right
            // now (mid-flight if the poll arrived early/late), not from its
            // previous target — avoids visible snaps on retarget.
            const t = Math.min(1, Math.max(0, (now - cur.tStart) / (cur.tEnd - cur.tStart)));
            const lonNow = cur.lon0 + (cur.lon1 - cur.lon0) * t;
            const latNow = cur.lat0 + (cur.lat1 - cur.lat0) * t;
            const bNow = lerpBearing(cur.b0, cur.b1, t);
            fleet.set(v.id, {
              lon0: lonNow, lat0: latNow, lon1: v.lon, lat1: v.lat,
              b0: bNow, b1: v.bearing,
              tStart: now, tEnd: now + POLL_MS,
              type: v.type, routeId: v.routeId,
            });
          }
        }
        // Drop vehicles that left the feed (went out of service).
        for (const id of fleet.keys()) {
          if (!seen.has(id)) fleet.delete(id);
        }

        setStatus({ count: data.count, updatedAt: data.updatedAt, error: null });
      } catch (err) {
        if (!cancelled) setStatus((s) => ({ ...s, error: String(err.message || err) }));
      } finally {
        if (!cancelled) timer = setTimeout(tick, POLL_MS);
      }
    }

    tick();
    return () => {
      cancelled = true;
      if (timer) clearTimeout(timer);
    };
  }, []);

  // Animation loop: sample every vehicle's glide each frame and repaint.
  useEffect(() => {
    let raf = null;

    function frame() {
      const fleet = fleetRef.current;
      if (overlayRef.current && fleet.size > 0) {
        const now = performance.now();
        const data = [];
        for (const [id, v] of fleet) {
          const t = Math.min(1, Math.max(0, (now - v.tStart) / (v.tEnd - v.tStart)));
          data.push({
            id,
            position: [v.lon0 + (v.lon1 - v.lon0) * t, v.lat0 + (v.lat1 - v.lat0) * t],
            bearing: lerpBearing(v.b0, v.b1, t),
            type: v.type,
            routeId: v.routeId,
          });
        }

        const use3d = zoomRef.current >= LOD_ZOOM;
        const layers = use3d
          ? ['bus', 'streetcar', 'subway'].map(
              (type) =>
                new ScenegraphLayer({
                  id: `vehicles-3d-${type}`,
                  data: data.filter((d) => d.type === type),
                  scenegraph: MODELS[type],
                  loaders: [GLTFLoader],
                  getPosition: (d) => d.position,
                  getOrientation: (d) => orientationForBearing(d.bearing),
                  sizeScale: SIZE_SCALE,
                  _lighting: 'pbr',
                  pickable: true,
                }),
            )
          : [
              new ScatterplotLayer({
                id: 'vehicles-dots',
                data,
                getPosition: (d) => d.position,
                getFillColor: (d) => COLORS[d.type] || COLORS.bus,
                getRadius: 40,
                radiusUnits: 'meters',
                radiusMinPixels: 2.5,
                radiusMaxPixels: 8,
                stroked: false,
                pickable: true,
              }),
            ];
        overlayRef.current.setProps({ layers });
      }
      raf = requestAnimationFrame(frame);
    }

    raf = requestAnimationFrame(frame);
    return () => cancelAnimationFrame(raf);
  }, []);

  return (
    <div style={{ position: 'absolute', inset: 0 }}>
      <div ref={containerRef} style={{ position: 'absolute', inset: 0 }} />
      <div
        style={{
          position: 'absolute',
          top: 12,
          left: 12,
          zIndex: 1,
          padding: '10px 12px',
          borderRadius: 10,
          background: 'rgba(17,17,20,0.82)',
          color: '#fff',
          font: '13px/1.4 system-ui, sans-serif',
          backdropFilter: 'blur(6px)',
          pointerEvents: 'none',
        }}
      >
        <div style={{ fontWeight: 700, marginBottom: 4 }}>TTC Live (dev)</div>
        {status.error ? (
          <div style={{ color: '#fca5a5' }}>feed error: {status.error}</div>
        ) : (
          <div>
            <span style={{ color: '#e11d2e' }}>●</span> bus &nbsp;
            <span style={{ color: '#f59e0b' }}>●</span> streetcar
            <div style={{ opacity: 0.7, marginTop: 3 }}>
              {status.count} vehicles
              {status.updatedAt
                ? ` · ${new Date(status.updatedAt * 1000).toLocaleTimeString()}`
                : ''}
            </div>
            <div style={{ opacity: 0.5, marginTop: 2 }}>
              zoom in past {LOD_ZOOM} for 3D vehicles
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
